name: expin_book
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  rxdart: ^0.27.5
  image_picker: ^0.8.5+3
  riverpod_annotation: ^1.0.4
  fl_chart: ^0.55.2
  permission_handler: ^10.2.0
  encrypt: ^5.0.1
  excel: ^2.0.0-null-safety-3
  file_picker: ^5.2.2
  flutter_local_notifications: ^9.1.4
  pdf: ^3.8.4
  printing: ^5.9.3
  floor: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  riverpod_generator: ^1.0.4
  floor_generator: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - fonts/

  fonts:
    - family: MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf
    
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100